# This entrypoint file to be used in development. Start by reading README.md
import password_cracker
from unittest import main

cracked_password1 = password_cracker.crack_sha1_hash(
    "62e7e355d5d8400fa8384448796af0bf6be4ffae")
print(cracked_password1)

cracked_password2 = password_cracker.crack_sha1_hash(
  # This is the hashcode generated by SHA-1 for 'football'..football is in the top 10000 database
    "7c4a8d09ca3762af61e59520943dc26494f8941b", use_salts=True)
print(cracked_password2)

# Run unit tests automatically
main(module='test_module', exit=False)
